### ISSUE TITLE
Inconsistency in value field update

### ISSUE THREAD

**Issue by alcibiade** [PolymerElements/iron-autogrow-textarea#57]
It seems that I can't update the value of the autogrow textarea directly:

![screenshot from 2015-11-09 22-07-57](https://cloud.githubusercontent.com/assets/3389277/11046559/6b95d5b4-872e-11e5-90fa-7ab6c8dc8c6a.png)

If I update it by assigning a value, nothing happens.

If I update the value attribute of the textarea field, the UI displays the updated value, but the outer textarea still returns the previous value.

Did I miss something there ?

**Comment by notwaldorf** [comment]
As mentioned in the docs (https://github.com/PolymerElements/iron-autogrow-textarea/blob/master/iron-autogrow-textarea.html#L26), you need to use `bindValue` if you want to bind to the native textarea's input. This is because imperatively updating `textarea.value` does not trigger any events (the property isn't observable), and the `iron-autogrow-textarea` is never notified.

See the demo for how `value` and `bind-value` work together: https://elements.polymer-project.org/elements/iron-autogrow-textarea?view=demo:demo/index.html&active=iron-autogrow-textarea
